import { Card, Input, TextArea, Button } from './basic';
import Grid from './Grid';
import Tab from './Tab';
import type { MaterialSchema } from '../types';

const materials: MaterialSchema[] = [
  {
    name: 'Card',
    label: '分组',
    type: 'layout',
    Component: Card,
    propsSchema: {
      title: {
        label: '标题',
        labelCol: { span: 6 },
        initialValue: '分组',
        rules: [{ required: true, message: '请输入标题' }],
        formType: 'Input',
        formProps: {},
      },
    },
    children: [],
  },
  {
    name: 'Grid',
    label: '栅格',
    type: 'builder',
    accept: false,
    Component: Grid,
    propsSchema: {
      cols: {
        label: '列数',
        labelCol: { span: 6 },
        initialValue: 2,
        rules: [{ required: true, message: '请输入列数' }],
        formType: 'InputNumber',
        formProps: {
          min: 1,
          max: 24,
          step: 1,
          precision: 0,
        },
      },
      justify: {
        label: '水平排列',
        labelCol: { span: 6 },
        initialValue: 'start',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'start', value: 'start' },
            { label: 'center', value: 'center' },
            { label: 'end', value: 'end' },
            { label: 'space-around', value: 'space-around' },
            { label: 'space-between', value: 'space-between' },
          ],
        },
      },
      align: {
        label: '垂直排列',
        labelCol: { span: 6 },
        initialValue: 'top',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'top', value: 'top' },
            { label: 'middle', value: 'middle' },
            { label: 'bottom', value: 'bottom' },
          ],
        },
      },
      gutter: {
        label: '间隔',
        labelCol: { span: 6 },
        initialValue: 0,
        formType: 'InputNumber',
        formProps: {
          min: 0,
          step: 1,
          precision: 0,
        },
      },
      // wrap: {
      //   label: '自动换行',
      //   labelCol: { span: 6 },
      //   initialValue: true,
      //   formType: 'Switch',
      //   valuePropName: 'checked',
      //   formProps: {},
      // },
    },
    children: [],
  },
  {
    name: 'Tab',
    label: '选项卡',
    type: 'builder',
    accept: false,
    Component: Tab,
    propsSchema: {
      tabPanes: {
        label: '选项',
        labelCol: { span: 6 },
        initialValue: [{ key: 'init', value: '标签项' }],
        rules: [{ required: true, type: 'array', message: '请添加选项' }],
        formType: 'SortableList',
        formProps: {
          placeholder: '请输入标签内容',
        },
      },
      type: {
        label: '类型',
        labelCol: { span: 6 },
        initialValue: 'line',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'line', value: 'line' },
            { label: 'card', value: 'card' },
            // { label: 'editable-card', value: 'editable-card' },
          ],
        },
      },
      size: {
        label: '尺寸',
        labelCol: { span: 6 },
        initialValue: 'default',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'default', value: 'default' },
            { label: 'large', value: 'large' },
            { label: 'small', value: 'small' },
          ],
        },
      },
      tabPosition: {
        label: '位置',
        labelCol: { span: 6 },
        initialValue: 'top',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'top', value: 'top' },
            { label: 'bottom', value: 'bottom' },
            { label: 'left', value: 'left' },
            { label: 'right', value: 'right' },
          ],
        },
      },
      tabBarGutter: {
        label: '间隔',
        labelCol: { span: 6 },
        initialValue: 0,
        formType: 'InputNumber',
        formProps: {
          min: 0,
          step: 1,
          precision: 0,
        },
      },
      centered: {
        label: '居中',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
    },
    children: [],
  },
  {
    name: 'Input',
    label: '单行文本',
    type: 'form',
    Component: Input,
    propsSchema: {
      defaultValue: {
        label: '默认值',
        labelCol: { span: 6 },
        formType: 'Input',
        formProps: {},
      },
      placeholder: {
        label: '提示',
        labelCol: { span: 6 },
        formType: 'Input',
        formProps: {},
      },
      type: {
        label: '类型',
        labelCol: { span: 6 },
        initialValue: 'text',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'text', value: 'text' },
            { label: 'password', value: 'password' },
            { label: 'file', value: 'file' },
            { label: 'search', value: 'search' },
            { label: 'email', value: 'email' },
            { label: 'number', value: 'number' },
            { label: 'tel', value: 'tel' },
            { label: 'url', value: 'url' },
            { label: 'button', value: 'button' },
            { label: 'color', value: 'color' },
            { label: 'checkbox', value: 'checkbox' },
            { label: 'radio', value: 'radio' },
            { label: 'range', value: 'range' },
            { label: 'image', value: 'image' },
            { label: 'hidden', value: 'hidden' },

            { label: 'date', value: 'date' },
            { label: 'datetime', value: 'datetime' },
            { label: 'datetime-local', value: 'datetime-local' },
            { label: 'month', value: 'month' },
            { label: 'week', value: 'week' },
            { label: 'time', value: 'time' },

            { label: 'reset', value: 'reset' },
            { label: 'submit', value: 'submit' },
          ],
        },
      },
      size: {
        label: '尺寸',
        labelCol: { span: 6 },
        initialValue: 'middle',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'large', value: 'large' },
            { label: 'middle', value: 'middle' },
            { label: 'small', value: 'small' },
          ],
        },
      },
      maxLength: {
        label: '最大长度',
        labelCol: { span: 6 },
        formType: 'InputNumber',
        formProps: {
          min: 0,
          step: 1,
          precision: 0,
        },
      },
      allowClear: {
        label: '清空',
        labelCol: { span: 6 },
        initialValue: true,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      bordered: {
        label: '边框',
        labelCol: { span: 6 },
        initialValue: true,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      disabled: {
        label: '禁用',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
    },
  },
  {
    name: 'TextArea',
    label: '多行文本',
    type: 'form',
    Component: TextArea,
    propsSchema: {
      defaultValue: {
        label: '默认值',
        labelCol: { span: 6 },
        formType: 'Input',
        formProps: {},
      },
      placeholder: {
        label: '提示',
        labelCol: { span: 6 },
        formType: 'Input',
        formProps: {},
      },
      size: {
        label: '尺寸',
        labelCol: { span: 6 },
        initialValue: 'middle',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'large', value: 'large' },
            { label: 'middle', value: 'middle' },
            { label: 'small', value: 'small' },
          ],
        },
      },
      maxLength: {
        label: '最大长度',
        labelCol: { span: 6 },
        formType: 'InputNumber',
        formProps: {
          min: 0,
          step: 1,
          precision: 0,
        },
      },
      rows: {
        label: '行数',
        labelCol: { span: 6 },
        formType: 'InputNumber',
        formProps: {
          min: 1,
          step: 1,
          precision: 0,
        },
      },
      autoSize: {
        label: '自适应',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      showCount: {
        label: '展示字数',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      allowClear: {
        label: '清空',
        labelCol: { span: 6 },
        initialValue: true,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      bordered: {
        label: '边框',
        labelCol: { span: 6 },
        initialValue: true,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      disabled: {
        label: '禁用',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
    },
  },
  {
    name: 'Button',
    label: '按钮',
    type: 'component',
    Component: Button,
    propsSchema: {
      children: {
        label: '文字',
        labelCol: { span: 6 },
        initialValue: '按钮',
        rules: [{ required: true, message: '请输入文字' }],
        formType: 'Input',
        formProps: {},
      },
      type: {
        label: '类型',
        labelCol: { span: 6 },
        initialValue: 'default',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'default', value: 'default' },
            { label: 'primary', value: 'primary' },
            { label: 'ghost', value: 'ghost' },
            { label: 'dashed', value: 'dashed' },
            { label: 'link', value: 'link' },
            { label: 'text', value: 'text' },
          ],
        },
      },
      shape: {
        label: '形状',
        labelCol: { span: 6 },
        initialValue: 'default',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'default', value: 'default' },
            { label: 'circle', value: 'circle' },
            { label: 'round', value: 'round' },
          ],
        },
      },
      size: {
        label: '尺寸',
        labelCol: { span: 6 },
        initialValue: 'middle',
        formType: 'Select',
        formProps: {
          options: [
            { label: 'large', value: 'large' },
            { label: 'middle', value: 'middle' },
            { label: 'small', value: 'small' },
          ],
        },
      },
      block: {
        label: '块级',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      danger: {
        label: '危险',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      ghost: {
        label: '幽灵',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
      loading: {
        label: '加载中',
        labelCol: { span: 6 },
        initialValue: false,
        formType: 'Switch',
        valuePropName: 'checked',
        formProps: {},
      },
    },
  },
];

export default materials;
